name = "your-worker-name"
main = "src/worker/index.ts"
compatibility_date = "2025-11-10"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# æ·»åŠ è¿™ä¸ªé…ç½®å—
[[d1_databases]]
binding = "DB" # ğŸš¨ è¿™ä¸ª "DB" å¿…é¡»å’Œä»£ç ä¸­çš„ c.env.DB åå­—ä¸€è‡´ï¼
database_name = "dbbinding" # ä½ åˆ›å»ºçš„æ•°æ®åº“åç§°
database_id = "c5ec5bd8-69c4-41af-b4fc-ef0c1853d9e3" # Wrangler æä¾›çš„æ•°æ®åº“ ID